Workflow Test

diff --git a/.github/workflows/renderDeploy.yml b/.github/workflows/renderDeploy.yml
--- a/.github/workflows/renderDeploy.yml
+++ b/.github/workflows/renderDeploy.yml
@@ -13,16 +13,47 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Node JS
+    - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '14'  
     
-    - name: Install NPM
+    - name: Install Dependencies
       run: npm install
 
     - name: Build
       run: npm ci && npm run build  
 
-    - name: Render Deployment
-      run: curl -X POST ${{ secrets.RENDER_DEPLOYAPI }}
+    - name: Deploy to Render
+      run: |
+        RESPONSE=$(curl -X POST -s -w "%{http_code}" -o output.txt ${{ secrets.RENDER_DEPLOYAPI }})
+        if [ "$RESPONSE" -ne 201 ]; then  
+          echo "Deployment failed with status $RESPONSE"
+          cat output.txt
+          exit 1
+        fi
+      env:
+        RENDER_DEPLOYAPI: ${{ secrets.RENDER_DEPLOYAPI }}
+
+    - name: Check Deployment Status
+      run: |
+        DEPLOY_ID=$(cat output.txt | jq -r '.id')
+        STATUS="unknown"
+        COUNTER=0
+        MAX_ATTEMPTS=30  # Limits the check to 5 minutes (10 seconds * 30)
+        until [[ "$STATUS" == "success" || "$COUNTER" -ge "$MAX_ATTEMPTS" ]]; do
+          sleep 10
+          RESULT=$(curl -s "https://api.render.com/deployments/$DEPLOY_ID/status" -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}")
+          STATUS=$(echo $RESULT | jq -r '.status')
+          if [ "$STATUS" == "failed" ]; then
+            echo "Deployment failed"
+            exit 1
+          fi
+          let COUNTER=COUNTER+1
+        done
+        if [ "$STATUS" != "success" ]; then
+          echo "Deployment did not succeed within the expected time."
+          exit 1
+        fi
+      env:
+        RENDER_API_TOKEN: ${{ secrets.RENDER_APIKEY }}
